import Head from 'next/head'
import styled from 'styled-components'

import App from '../components/App'

import 'antd/dist/antd.css'

const Container = styled.div`
  width: 100%;
  height: 100%;
`

const Home = () => {
  return (
    <Container>
      <Head>
        <title>Pokéguess</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <App />
    </Container>
  )
}

export default Home
