import Head from 'next/head'
import App from '../components/App'

const Home = () => {
  return (
    <>
      <Head>
        <title>Pokéguess</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <App />
    </>
  )
}

export default Home
